stages:
    - security-scanner
    - code-quality
    - code-tests
php-lint:
    cache:
        key:
            files:
                - composer.lock
            prefix: 'php${php_version}-'
        paths:
            - ./cache/composer
    before_script:
        - 'set -xe'
        - 'apt-get update -yqq'
        - 'apt-get install git libzip-dev unzip parallel libxml2-utils wget wait-for-it libicu-dev -yqq'
        - 'php -r "readfile(''http://getcomposer.org/installer'');" | php -- --install-dir=/usr/local/bin/ --filename=composer'
        - 'chmod +x /usr/local/bin/composer'
        - 'composer config cache-dir ./cache/composer'
        - 'cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini'
        - 'awk ''/^error_reporting = E_ALL/{print "error_reporting = E_ALL & ~E_DEPRECATED"; next}1'' /usr/local/etc/php/php.ini > temp.ini && mv temp.ini /usr/local/etc/php/php.ini'
    image: 'php:${php_version}'
    stage: php-lint
    script:
        - 'composer ci:php:lint'
    parallel:
        matrix:
            -
                php_version:
                    - 8.1
                    - 8.2
code-quality:
    cache:
        key:
            files:
                - composer.lock
            prefix: 'php${php_version}-typo3{typo3_version}-'
        paths:
            - ./cache/composer
    before_script:
        - 'set -xe'
        - 'apt-get update -yqq'
        - 'apt-get install git libzip-dev unzip parallel libxml2-utils wget wait-for-it libicu-dev -yqq'
        - 'php -r "readfile(''http://getcomposer.org/installer'');" | php -- --install-dir=/usr/local/bin/ --filename=composer'
        - 'chmod +x /usr/local/bin/composer'
        - 'composer config cache-dir ./cache/composer'
        - 'cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini'
        - 'awk ''/^error_reporting = E_ALL/{print "error_reporting = E_ALL & ~E_DEPRECATED"; next}1'' /usr/local/etc/php/php.ini > temp.ini && mv temp.ini /usr/local/etc/php/php.ini'
        - 'composer require typo3/cms-core ^${typo3_version} --no-progress --ignore-platform-req=ext-intl'
        - 'composer install --no-progress --ignore-platform-req=ext-intl'
    image: 'php:${php_version}'
    stage: code-quality
    script:
        - 'composer ci'
        - 'composer ci:json:lint'
        - 'composer ci:php:rector'
        - 'composer ci:php:cs-fixer'
        - 'composer ci:php:stan'
    parallel:
        matrix:
            -
                php_version:
                    - '8.1'
                    - '8.2'
                typo3_version:
                    - '11.5'
                    - '12.4'
code-tests:
    cache:
        key:
            files:
                - composer.lock
            prefix: 'php${php_version}-typo3{typo3_version}-'
        paths:
            - ./cache/composer
    before_script:
        - 'set -xe'
        - 'apt-get update -yqq'
        - 'apt-get install git libzip-dev unzip parallel libxml2-utils wget wait-for-it libicu-dev -yqq'
        - 'php -r "readfile(''http://getcomposer.org/installer'');" | php -- --install-dir=/usr/local/bin/ --filename=composer'
        - 'chmod +x /usr/local/bin/composer'
        - 'composer config cache-dir ./cache/composer'
        - 'cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini'
        - 'awk ''/^error_reporting = E_ALL/{print "error_reporting = E_ALL & ~E_DEPRECATED"; next}1'' /usr/local/etc/php/php.ini > temp.ini && mv temp.ini /usr/local/etc/php/php.ini'
        - 'composer require typo3/cms-core ^${typo3_version} --no-progress --ignore-platform-req=ext-intl'
        - 'composer install --no-progress --ignore-platform-req=ext-intl'
    image: 'php:${php_version}'
    stage: code-tests
    script:
        - 'composer ci:coverage'
    parallel:
        matrix:
            -
                php_version:
                    - 8.1
                    - 8.2
                typo3_version:
                    - 11.5
                    - 12.4
workflow:
    rules:
        -
            if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
        -
            if: $CI_COMMIT_TAG
        -
            if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
semgrep:
    image: semgrep/semgrep
    script: 'semgrep scan --config auto --error .'
    stage: security-scanner
trivy:
    stage: security-scanner
    image: 'docker:stable'
    services:
        -
            name: 'docker:dind'
            entrypoint:
                - env
                - '-u'
                - DOCKER_HOST
            command:
                - dockerd-entrypoint.sh
    variables:
        DOCKER_HOST: 'tcp://docker:2375/'
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ''
    before_script:
        - 'export TRIVY_VERSION=$(wget -qO - "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep ''"tag_name":'' | sed -E ''s/.*"v([^"]+)".*/\1/'')'
        - 'echo $TRIVY_VERSION'
        - 'wget --no-verbose https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz -O - | tar -zxvf -'
    allow_failure: false
    script:
        - './trivy fs --exit-code 1 --cache-dir .trivycache/ --no-progress --format table --vuln-type library --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL  ./'
    cache:
        paths:
            - .trivycache/
