services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DigitalMarketingFramework\Typo3\StaticInfoTables\:
    resource: '../Classes/*'

  # static configuration document update
  DigitalMarketingFramework\Typo3\StaticInfoTables\ConfigurationDocument\Storage\EventListener\StaticInfoSystemConfigurationDocumentEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\ConfigurationDocument\Storage\Event\StaticConfigurationDocumentIdentifierCollectionEvent
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\ConfigurationDocument\Storage\Event\StaticConfigurationDocumentLoadEvent
