'on':
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    php-lint:
        name: 'PHP linter'
        runs-on: ubuntu-22.04
        steps:
            -
                name: Checkout
                uses: actions/checkout@v4
            -
                name: 'Install PHP'
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '${{ matrix.php_version }}'
                    coverage: none
                    tools: 'composer:v2.4'
            -
                name: 'Show the Composer configuration'
                run: 'composer config --global --list'
            -
                name: 'Run PHP lint'
                run: 'composer ci:php:lint'
        strategy:
            fail-fast: false
            matrix:
                php_version:
                    - 8.1
                    - 8.2
    code-quality:
        name: 'Code quality checks'
        runs-on: ubuntu-22.04
        steps:
            -
                name: Checkout
                uses: actions/checkout@v4
            -
                name: 'Install PHP'
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '${{ matrix.php_version }}'
                    coverage: none
                    tools: 'composer:v2.4'
            -
                name: 'Show Composer version'
                run: 'composer --version'
            -
                name: 'Show the Composer configuration'
                run: 'composer config --global --list'
            -
                name: 'Cache dependencies installed with composer'
                uses: actions/cache@v3
                with:
                    key: 'php${{ matrix.php_version }}-typo3${{ matrix.typo3_version }}'
                    path: ~/.cache/composer
                    restore-keys: "php${{ matrix.php_version }}-composer-\n"
            -
                name: 'Install Composer dependencies'
                run: "composer require typo3/cms-core ^${{ matrix.typo3_version }} --no-progress\ncomposer install --no-progress\n"
            -
                name: 'Run command'
                run: "composer ci\n"
        strategy:
            fail-fast: false
            matrix:
                php_version:
                    - '8.1'
                    - '8.2'
                typo3_version:
                    - '11.5'
                    - '12.4'
    code-tests:
        name: 'Coverage tests'
        runs-on: ubuntu-22.04
        env:
          DB_DATABASE: typo3
          DB_USER: root
          DB_PASSWORD: root
          DB_HOST: localhost
        steps:
            -
                name: Checkout
                uses: actions/checkout@v4
            -
                name: 'Install PHP'
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '${{ matrix.php_version }}'
                    coverage: none
                    tools: 'composer:v2.4'
                    extensions: mysqli
            -
                name: 'Show Composer version'
                run: 'composer --version'
            -
                name: 'Show the Composer configuration'
                run: 'composer config --global --list'
            -
                name: 'Cache dependencies installed with composer'
                uses: actions/cache@v3
                with:
                    key: 'php${{ matrix.php_version }}-typo3${{ matrix.php_version }}'
                    path: ~/.cache/composer
                    restore-keys: "php${{ matrix.php_version }}-composer-\n"
            -
                name: 'Install Composer dependencies'
                run: "composer require typo3/cms-core ^${{ matrix.typo3_version }} --no-progress\ncomposer install --no-progress\n"
            -
                name: "Start MySQL"
                run: "sudo /etc/init.d/mysql start"
            - run: |
                export typo3DatabaseName="$DB_DATABASE";
                export typo3DatabaseHost="$DB_HOST";
                export typo3DatabaseUsername="$DB_USER";
                export typo3DatabasePassword="$DB_PASSWORD";
                composer ci:coverage
        strategy:
            fail-fast: false
            matrix:
                php_version:
                    - 8.1
                    - 8.2
                typo3_version:
                    - 11.5
                    - 12.4
    trivy:
        name: trivy
        runs-on: ubuntu-latest
        steps:
            -
                name: 'Checkout code'
                uses: actions/checkout@v3
            -
                name: 'Run Trivy vulnerability scanner in repo mode'
                uses: aquasecurity/trivy-action@0.20.0
                with:
                    scan-type: fs
                    scan-ref: .
                    format: table
                    vuln-type: library
                    severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
                    exit-code: '1'
    semgrep:
        name: semgrep
        runs-on: ubuntu-latest
        container:
            image: semgrep/semgrep
        if: "(github.actor != 'dependabot[bot]')"
        steps:
            -
                uses: actions/checkout@v4
            -
                run: 'semgrep scan --config auto --error'
permissions:
    contents: read
